apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: mealie
  name: mealie
  namespace: mealie
  resourceVersion: "22211"
  uid: b03f792e-d00b-46eb-a8bc-fe0d938555b8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.2.0
        imagePullPolicy: Always
        name: mealie
        ports:
          - containerPort: 9000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
